// =============================================================================
// Emitters — pure `(model) => string` functions, one per generated file. Each
// mirrors the equivalent error_log file so generated code reads like the
// hand-written feature. Nothing here touches the DB or the filesystem.
// =============================================================================

import type { FeatureModel, FieldModel, ProcInfo, ProcParam } from './model.js';
import { enumConstName, enumTypeName } from './names.js';
import { renderColumnType } from './typemap.js';

const GENERATED_BY = 'Generated by `pnpm gen:feature` from the live database.';

function fieldsByName(model: FeatureModel): Map<string, FieldModel> {
  return new Map(model.fields.map((f) => [f.name, f]));
}

/** TS type of a single column by name (for PK args / inputs); falls back to string. */
function tsTypeOf(model: FeatureModel, columnName: string): string {
  return fieldsByName(model).get(columnName)?.ts ?? 'string';
}

// -----------------------------------------------------------------------------
// 1. Shared types — packages/types/src/<table>.ts
// -----------------------------------------------------------------------------

export function emitTypes(model: FeatureModel): string {
  const { table, entity } = model;
  const lines: string[] = [];

  lines.push('// =============================================================================');
  lines.push(`// ${entity} domain — row model and zod schema.`);
  lines.push('//');
  lines.push(`// ${GENERATED_BY} The schema is the single source of truth; \`${entity}\` is`);
  lines.push('// inferred from it and the @app/db test suite validates real proc output against');
  lines.push('// it with `.strict()`, so the column set must match the select proc exactly.');
  lines.push('// =============================================================================');
  lines.push('');
  lines.push("import { z } from 'zod';");
  lines.push('');

  // Enum vocabularies, one per enum-constrained column.
  const enumFields = model.fields.filter((f) => f.enumValues && f.enumValues.length > 0);
  for (const f of enumFields) {
    const constName = enumConstName(table, f.name);
    const typeName = enumTypeName(table, f.name);
    const values = (f.enumValues ?? []).map((v) => `'${v.replace(/'/g, "\\'")}'`).join(', ');
    lines.push(`export const ${constName} = [${values}] as const;`);
    lines.push(`export type ${typeName} = (typeof ${constName})[number];`);
    lines.push('');
  }

  lines.push(`export const ${entity}Schema = z.object({`);
  for (const f of model.fields) {
    lines.push(`  ${f.name}: ${f.zod},`);
  }
  lines.push('});');
  lines.push(`export type ${entity} = z.infer<typeof ${entity}Schema>;`);
  lines.push('');

  return lines.join('\n');
}

// -----------------------------------------------------------------------------
// DDL reconstruction (shared by the migration and the table snapshot)
// -----------------------------------------------------------------------------

function renderTableDdl(model: FeatureModel): string {
  const { table } = model;
  const singleColPk = model.pkColumns.length === 1 ? model.pkColumns[0] : null;
  const checksByColumn = new Map<string, string[]>();
  const tableChecks: string[] = [];
  for (const c of model.checks) {
    const clause = `CONSTRAINT ${c.name} CHECK ${c.definition}`;
    if (c.columnName) {
      const arr = checksByColumn.get(c.columnName) ?? [];
      arr.push(clause);
      checksByColumn.set(c.columnName, arr);
    } else {
      tableChecks.push(clause);
    }
  }
  const defaultsByColumn = new Map<string, string>();
  for (const d of model.defaults) {
    defaultsByColumn.set(d.columnName, `CONSTRAINT ${d.name} DEFAULT ${d.definition}`);
  }

  const lines: string[] = [];
  for (const col of model.columns) {
    if (col.isComputed) continue; // computed columns aren't part of the insertable shape
    const parts: string[] = [col.name, renderColumnType(col)];
    if (col.isIdentity) parts.push('IDENTITY (1, 1)');
    parts.push(col.isNullable ? 'NULL' : 'NOT NULL');
    if (singleColPk && col.name === singleColPk) {
      parts.push(`CONSTRAINT pk_${table} PRIMARY KEY`);
    }
    const def = defaultsByColumn.get(col.name);
    if (def) parts.push(def);
    for (const chk of checksByColumn.get(col.name) ?? []) parts.push(chk);
    lines.push(`  ${parts.join(' ')}`);
  }
  if (!singleColPk && model.pkColumns.length > 0) {
    lines.push(`  CONSTRAINT pk_${table} PRIMARY KEY (${model.pkColumns.join(', ')})`);
  }
  for (const chk of tableChecks) lines.push(`  ${chk}`);

  return `CREATE TABLE dbo.${table} (\n${lines.join(',\n')}\n);`;
}

function renderIndexDdls(model: FeatureModel): string[] {
  return model.indexes.map((idx) => {
    const cols = idx.columns.map((c) => `${c.name}${c.descending ? ' DESC' : ''}`).join(', ');
    const unique = idx.isUnique ? 'UNIQUE ' : '';
    return `CREATE ${unique}INDEX ${idx.name} ON dbo.${model.table} (${cols});`;
  });
}

// -----------------------------------------------------------------------------
// 2. Migration — packages/db/src/migrations/NNN_<table>.sql (+ .down.sql)
// -----------------------------------------------------------------------------

export function emitMigration(model: FeatureModel): string {
  const { table } = model;
  const out: string[] = [];

  out.push('-- =============================================================================');
  out.push(`-- ${table} data layer (IIS / SQL Server).`);
  out.push('--');
  out.push(`-- ${GENERATED_BY} Authored to this project's stored-procedure convention`);
  out.push('-- (see CLAUDE.md and the mssql-function-authoring skill). The table create is');
  out.push('-- guarded so re-running against a DB that already has the table is a no-op, and');
  out.push('-- the procs are CREATE OR ALTER (idempotent).');
  out.push('-- =============================================================================');
  out.push('');
  out.push('SET QUOTED_IDENTIFIER ON;');
  out.push('GO');
  out.push('SET ANSI_NULLS ON;');
  out.push('GO');
  out.push('');
  out.push("IF SCHEMA_ID('crd') IS NULL EXEC ('CREATE SCHEMA crd');");
  out.push('GO');
  out.push('');

  // Table + indexes, guarded as one batch.
  const tableDdl = renderTableDdl(model);
  const indexDdls = renderIndexDdls(model);
  const guardedInner = [tableDdl, ...indexDdls]
    .join('\n')
    .split('\n')
    .map((l) => (l.length > 0 ? `  ${l}` : l))
    .join('\n');
  out.push(`IF OBJECT_ID('dbo.${table}', 'U') IS NULL`);
  out.push('BEGIN');
  out.push(guardedInner);
  out.push('END');
  out.push('GO');
  out.push('');

  // CRUD procs, verbatim from the catalog (already CREATE OR ALTER).
  for (const proc of Object.values(model.procs)) {
    if (!proc) continue;
    out.push(proc.definition.trim());
    out.push('GO');
    out.push('');
  }

  return out.join('\n');
}

export function emitMigrationDown(model: FeatureModel): string {
  const { table } = model;
  const out: string[] = [];
  out.push(`-- Revert: drop the ${table} CRUD procs, then the table.`);
  // Drop procs (delete/count/list/select/update/insert order is arbitrary; all IF EXISTS).
  for (const proc of Object.values(model.procs)) {
    if (!proc) continue;
    out.push(`DROP PROCEDURE IF EXISTS ${proc.name};`);
    out.push('GO');
  }
  out.push(`DROP TABLE IF EXISTS dbo.${table};`);
  out.push('GO');
  return out.join('\n');
}

// -----------------------------------------------------------------------------
// 3. Snapshots — schema/tables/<table>.sql and schema/stored-procedures/*.sql
// -----------------------------------------------------------------------------

export function emitTableSnapshot(model: FeatureModel): string {
  const out: string[] = [];
  out.push(`-- Snapshot of dbo.${model.table}. ${GENERATED_BY} Keep in sync in the same commit.`);
  out.push(renderTableDdl(model));
  out.push('GO');
  for (const idx of renderIndexDdls(model)) {
    out.push(idx);
    out.push('GO');
  }
  return out.join('\n') + '\n';
}

/** One snapshot file per existing proc — keyed by `crd.<proc>` for the contract test. */
export function emitProcSnapshots(model: FeatureModel): { fileName: string; content: string }[] {
  const files: { fileName: string; content: string }[] = [];
  for (const proc of Object.values(model.procs)) {
    if (!proc) continue;
    const content = [
      `-- Snapshot of ${proc.name}. ${GENERATED_BY}`,
      proc.definition.trim(),
      'GO',
      '',
    ].join('\n');
    files.push({ fileName: `${proc.name}.sql`, content });
  }
  return files;
}

// -----------------------------------------------------------------------------
// 4. Repository — packages/db/src/repositories/<table>.repo.ts
// -----------------------------------------------------------------------------

/** Build the value expression bound for a proc param in a callProc map. */
function paramValueExpr(model: FeatureModel, param: ProcParam): string {
  if (model.jsonColumns.includes(param.name)) {
    return `input.${param.name} === undefined ? null : JSON.stringify(input.${param.name})`;
  }
  return `input.${param.name} ?? null`;
}

function emitInputInterface(model: FeatureModel, name: string, params: ProcParam[]): string {
  const lines = [`export interface ${name} {`];
  for (const p of params) {
    const optional = p.hasDefault ? '?' : '';
    const ts = model.jsonColumns.includes(p.name) ? 'unknown' : tsTypeOf(model, p.name);
    lines.push(`  ${p.name}${optional}: ${ts};`);
  }
  lines.push('}');
  return lines.join('\n');
}

export function emitRepository(model: FeatureModel): string {
  const { entity, procs, selectKeyParam } = model;
  const pkCol = model.pkColumns[0] ?? null;
  const pkTs = pkCol ? tsTypeOf(model, pkCol) : 'number';
  const out: string[] = [];

  out.push('// =============================================================================');
  out.push(`// ${entity} repository.`);
  out.push('//');
  out.push(`// ${GENERATED_BY} Reads and writes go through [crd] stored procedures (the only`);
  out.push('// door into the tables). Every proc takes the acting user as its first param');
  out.push('// (@user_id), recorded to procedure_history and, on insert, stored as created_by.');
  out.push('// `getById` and `list` share crd.<table>_select: getById passes the key, list');
  out.push('// passes null.');
  out.push('// =============================================================================');
  out.push('');
  out.push("import { callProc } from '../client.js';");
  out.push("import type { DbExecutor } from '../connection.js';");
  out.push('');
  out.push('/** Fallback actor when no authenticated user is in scope. */');
  out.push("const SYSTEM_ACTOR = 'system';");
  out.push('');

  // Row type — same shape the schema validates.
  out.push(`export interface ${entity}Row {`);
  for (const f of model.fields) out.push(`  ${f.name}: ${f.ts};`);
  out.push('}');
  out.push('');

  // Input interfaces.
  const insertProc = procs.insert;
  const updateProc = procs.update;
  if (insertProc) {
    const params = insertProc.params.filter((p) => p.name !== 'user_id');
    out.push(emitInputInterface(model, `${entity}InsertInput`, params));
    out.push('');
  }
  if (updateProc) {
    const params = updateProc.params.filter(
      (p) => p.name !== 'user_id' && p.name !== selectKeyParam,
    );
    out.push(emitInputInterface(model, `${entity}UpdateInput`, params));
    out.push('');
  }

  out.push(`export class ${entity}Repo {`);
  out.push('  constructor(private readonly db: DbExecutor) {}');
  out.push('');

  // insert
  if (insertProc) {
    const params = insertProc.params.filter((p) => p.name !== 'user_id');
    out.push(
      `  async insert(input: ${entity}InsertInput, actor: string = SYSTEM_ACTOR): Promise<${entity}Row> {`,
    );
    out.push(`    const rows = await callProc<${entity}Row>(this.db, '${insertProc.name}', {`);
    out.push('      user_id: actor,');
    for (const p of params) out.push(`      ${p.name}: ${paramValueExpr(model, p)},`);
    out.push('    });');
    out.push(`    if (!rows[0]) throw new Error('${insertProc.name} returned no row');`);
    out.push('    return rows[0];');
    out.push('  }');
    out.push('');
  }

  // update
  if (updateProc && selectKeyParam) {
    const params = updateProc.params.filter(
      (p) => p.name !== 'user_id' && p.name !== selectKeyParam,
    );
    out.push(
      `  async update(id: ${pkTs}, input: ${entity}UpdateInput, actor: string = SYSTEM_ACTOR): Promise<${entity}Row | null> {`,
    );
    out.push(`    const rows = await callProc<${entity}Row>(this.db, '${updateProc.name}', {`);
    out.push('      user_id: actor,');
    out.push(`      ${selectKeyParam}: id,`);
    for (const p of params) out.push(`      ${p.name}: ${paramValueExpr(model, p)},`);
    out.push('    });');
    out.push('    return rows[0] ?? null;');
    out.push('  }');
    out.push('');
  }

  // delete
  const deleteProc = procs.delete;
  if (deleteProc && selectKeyParam) {
    out.push(`  async delete(id: ${pkTs}, actor: string = SYSTEM_ACTOR): Promise<void> {`);
    out.push(
      `    await callProc(this.db, '${deleteProc.name}', { user_id: actor, ${selectKeyParam}: id });`,
    );
    out.push('  }');
    out.push('');
  }

  // getById + list (shared select)
  const selectProc = procs.select;
  if (selectProc && selectKeyParam) {
    out.push(
      `  async getById(id: ${pkTs}, actor: string = SYSTEM_ACTOR): Promise<${entity}Row | null> {`,
    );
    out.push(`    const rows = await callProc<${entity}Row>(this.db, '${selectProc.name}', {`);
    out.push('      user_id: actor,');
    out.push(`      ${selectKeyParam}: id,`);
    out.push('    });');
    out.push('    return rows[0] ?? null;');
    out.push('  }');
    out.push('');
    out.push(`  async list(actor: string = SYSTEM_ACTOR): Promise<${entity}Row[]> {`);
    out.push(`    return callProc<${entity}Row>(this.db, '${selectProc.name}', {`);
    out.push('      user_id: actor,');
    out.push(`      ${selectKeyParam}: null,`);
    out.push('    });');
    out.push('  }');
    out.push('');
  }

  // count + listPage (only when a count proc exists or was synthesized)
  const countProc = procs.count;
  if (countProc) {
    out.push(`  /** Total rows — powers "page X of Y" alongside list(). */`);
    out.push(`  async count(actor: string = SYSTEM_ACTOR): Promise<number> {`);
    out.push(
      `    const rows = await callProc<{ total: number }>(this.db, '${countProc.name}', { user_id: actor });`,
    );
    out.push('    return rows[0]?.total ?? 0;');
    out.push('  }');
    out.push('');
    if (selectProc && selectKeyParam) {
      out.push(`  /** One listing plus its total, for a paged UI. */`);
      out.push(
        `  async listPage(actor: string = SYSTEM_ACTOR): Promise<{ rows: ${entity}Row[]; total: number }> {`,
      );
      out.push('    const rows = await this.list(actor);');
      out.push('    const total = await this.count(actor);');
      out.push('    return { rows, total };');
      out.push('  }');
      out.push('');
    }
  }

  while (out[out.length - 1] === '') out.pop();
  out.push('}');
  out.push('');
  return out.join('\n');
}

/**
 * A conventional `crd.<table>_count` proc — used when the DB has no count proc
 * but the caller wants one (`--with-count`). Follows the project's proc rules:
 * `@user_id` first, the procedure_history audit call, SET NOCOUNT ON, and a
 * single `{ total }` row.
 */
export function synthesizeCountProc(table: string): ProcInfo {
  const definition = [
    `CREATE OR ALTER PROCEDURE crd.${table}_count`,
    '  @user_id varchar(20)',
    'AS',
    'BEGIN',
    '  -- =========================================================================',
    `  -- Procedure Name : crd.${table}_count`,
    `  -- Purpose        : Total rows in dbo.${table}; powers list paging / "X of Y".`,
    '  -- Params         : @user_id - calling user',
    '  -- Returns        : one row, one column: total (int)',
    '  -- =========================================================================',
    '  SET NOCOUNT ON;',
    '  EXECUTE [crd].[procedure_history_insert] @user_id = @user_id, @proc_id = @@PROCID;',
    '',
    `  SELECT COUNT(*) AS total FROM dbo.${table};`,
    'END',
  ].join('\n');

  return {
    action: 'count',
    name: `crd.${table}_count`,
    definition,
    params: [{ name: 'user_id', sqlType: 'varchar', hasDefault: false, maxLength: 20 }],
    synthesized: true,
  };
}

// -----------------------------------------------------------------------------
// 5. Test — packages/db/test/<table>.test.ts
// -----------------------------------------------------------------------------

/** A plausible literal for a proc-input field, by its row-field type. */
function sampleValue(model: FeatureModel, param: ProcParam): string {
  if (model.jsonColumns.includes(param.name)) return '{ sample: true }';
  const field = fieldsByName(model).get(param.name);
  if (field?.enumValues && field.enumValues[0])
    return `'${field.enumValues[0].replace(/'/g, "\\'")}'`;
  const ts = (field?.ts ?? 'string').replace(' | null', '');
  if (ts === 'number') return '1';
  if (ts === 'boolean') return 'true';
  return "'test'";
}

/** Can this field be read back and compared with `toBe` (a non-JSON primitive)? */
function isComparableScalar(model: FeatureModel, param: ProcParam): boolean {
  if (model.jsonColumns.includes(param.name)) return false;
  const field = fieldsByName(model).get(param.name);
  if (!field) return false;
  if (field.enumValues) return field.enumValues.length >= 2; // need a second value to change to
  const ts = field.ts.replace(' | null', '');
  return ts === 'string' || ts === 'number' || ts === 'boolean';
}

/** A literal that differs from sampleValue(), so an update is observably applied. */
function mutatedLiteral(model: FeatureModel, param: ProcParam): string {
  const field = fieldsByName(model).get(param.name);
  if (field?.enumValues && field.enumValues.length >= 2) {
    return `'${(field.enumValues[1] as string).replace(/'/g, "\\'")}'`;
  }
  const ts = (field?.ts ?? 'string').replace(' | null', '');
  if (ts === 'number') return '2';
  if (ts === 'boolean') return 'false';
  return "'updated'";
}

export function emitTest(model: FeatureModel): string {
  const { table, entity, procs, selectKeyParam } = model;
  const pkCol = model.pkColumns[0] ?? 'id';
  const insertProc = procs.insert;
  const out: string[] = [];

  out.push('// =============================================================================');
  out.push(`// ${table} data-layer test — validates the T-SQL ↔ TypeScript/zod seam.`);
  out.push('//');
  out.push(`// ${GENERATED_BY} Walks the full CRUD lifecycle — insert, confirm it exists (raw`);
  out.push(`// select row parsed with ${entity}Schema.strict()), update a field and confirm the`);
  out.push('// new value round-trips, then delete and confirm it is gone. Runs inside a');
  out.push('// rolled-back transaction (see support/db.ts).');
  out.push('// =============================================================================');
  out.push('');
  out.push("import { describe, expect } from 'vitest';");
  out.push('');
  out.push(`import { ${entity}Repo } from '@app/db';`);
  out.push(`import { ${entity}Schema } from '@app/types';`);
  out.push('');
  out.push("import { test } from './support/db';");
  out.push('');
  out.push(`describe('${table} data layer', () => {`);
  out.push("  test('insert → read → update → delete round-trips', async ({ db }) => {");
  out.push(`    const repo = new ${entity}Repo(db);`);
  out.push('');

  if (insertProc) {
    const hasSelect = selectProcAndKey(model);

    // 1. Insert.
    const insertParams = insertProc.params.filter((p) => p.name !== 'user_id');
    out.push('    // 1. Insert a row.');
    out.push('    const created = await repo.insert(');
    out.push('      {');
    for (const p of insertParams) out.push(`        ${p.name}: ${sampleValue(model, p)},`);
    out.push('      },');
    out.push("      'tester',");
    out.push('    );');
    out.push(`    const id = created.${pkCol};`);
    out.push('    expect(id).toBeDefined();');
    out.push('');

    // 2. Confirm it exists.
    if (hasSelect) {
      out.push('    // 2. It exists: the raw select row matches the schema, and getById finds it.');
      out.push(
        `    const raw = await db.query(\`EXEC ${procs.select?.name} @user_id = @p0, @${selectKeyParam} = @p1\`, [`,
      );
      out.push("      'tester',");
      out.push('      String(id),');
      out.push('    ]);');
      out.push(`    expect(() => ${entity}Schema.strict().parse(raw.rows[0])).not.toThrow();`);
      out.push('');
      out.push(`    const found = await repo.getById(id, 'tester');`);
      out.push('    expect(found).not.toBeNull();');
      out.push(`    expect(found?.${pkCol}).toBe(id);`);
      out.push(
        `    expect((await repo.list('tester')).some((r) => r.${pkCol} === id)).toBe(true);`,
      );
      out.push('');
    }

    if (procs.count) {
      out.push('    // The count proc sees the new row.');
      out.push(`    expect(await repo.count('tester')).toBeGreaterThan(0);`);
      out.push('');
    }

    // 3. Update a field and confirm the new value persisted.
    if (procs.update && selectKeyParam) {
      const upParams = procs.update.params.filter(
        (p) => p.name !== 'user_id' && p.name !== selectKeyParam,
      );
      const target = upParams.find((p) => isComparableScalar(model, p));
      out.push('    // 3. Update a field and confirm the change round-trips.');
      out.push('    const updated = await repo.update(');
      out.push('      id,');
      out.push('      {');
      for (const p of upParams) {
        const literal =
          target && p.name === target.name ? mutatedLiteral(model, p) : sampleValue(model, p);
        out.push(`        ${p.name}: ${literal},`);
      }
      out.push('      },');
      out.push("      'tester',");
      out.push('    );');
      out.push('    expect(updated).not.toBeNull();');
      if (target) {
        const literal = mutatedLiteral(model, target);
        out.push(`    expect(updated?.${target.name}).toBe(${literal});`);
        if (hasSelect) {
          out.push(
            `    expect((await repo.getById(id, 'tester'))?.${target.name}).toBe(${literal});`,
          );
        }
      } else {
        // No comparable scalar column to mutate — assert identity only.
        out.push(`    expect(updated?.${pkCol}).toBe(id);`);
      }
      out.push('');
    }

    // 4. Delete and confirm it is gone.
    if (procs.delete && selectKeyParam) {
      out.push('    // 4. Delete, then confirm it is gone.');
      out.push(`    await repo.delete(id, 'tester');`);
      if (hasSelect) out.push(`    expect(await repo.getById(id, 'tester')).toBeNull();`);
      out.push('');
    }
  } else {
    out.push('    // No insert proc found — nothing to seed; extend this test by hand.');
    out.push('    expect(repo).toBeDefined();');
  }

  while (out[out.length - 1] === '') out.pop();
  out.push('  });');
  out.push('});');
  out.push('');
  return out.join('\n');
}

function selectProcAndKey(model: FeatureModel): boolean {
  return Boolean(model.procs.select && model.selectKeyParam);
}
